initNavigation('colors.html');
let rows=[],editing=null;
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function fallback(value){const key=String(value||'').toLowerCase(),map={black:'#111',white:'#eee',red:'#b71c1c',orange:'#f47b20',yellow:'#f6c21a',green:'#159947',blue:'#1464d2',purple:'#6936c9',pink:'#e15aa2',gray:'#888',grey:'#888',brown:'#8b5a2b',gold:'#caa45f',silver:'#c0c0c0',olive:'#808000',teal:'#17a2a6'};const match=Object.keys(map).find(name=>key.includes(name));return match?map[match]:'#d8d8d8'}
function grouped(list){const groups=new Map();list.forEach(row=>{const brand=(row.brand||'No Brand').trim()||'No Brand';if(!groups.has(brand))groups.set(brand,[]);groups.get(brand).push(row)});return [...groups].sort((a,b)=>a[0].localeCompare(b[0]))}
function ensureColorUiStyles(){if(document.getElementById('colorUiAdditions'))return;const style=document.createElement('style');style.id='colorUiAdditions';style.textContent=`.filament-title-row{display:flex;align-items:center;gap:10px;width:100%}.color-count-pill{display:inline-grid;place-items:center;min-width:30px;height:24px;padding:0 8px;border:1px solid #8b6420;border-radius:999px;background:linear-gradient(180deg,#23190c,#120f09);color:#efb952;font-size:10px;font-weight:900;line-height:1;white-space:nowrap}.color-count-pill.total{min-width:34px;height:26px;font-size:11px}.color-card{position:relative}.color-card-status{position:absolute;right:11px;top:7px;display:grid;place-items:center;width:18px;height:18px;border-radius:50%;font:900 11px/1 Arial,sans-serif;z-index:3}.color-card-status.active{border:1px solid #3f8f46;background:#123618;color:#80e188}.color-card-status.inactive{border:1px solid #a13c32;background:#471612;color:#ff8278}.color-card .small-btn,.color-card .color-edit-btn{margin-top:20px}`;document.head.appendChild(style)}
function updateTotalCount(count){ensureColorUiStyles();const head=document.querySelector('.v7-card-head'),title=head?.querySelector('h2');if(!head||!title)return;head.classList.add('filament-title-row');let pill=$('totalColorCount');if(!pill){pill=document.createElement('span');pill.id='totalColorCount';pill.className='color-count-pill total';title.insertAdjacentElement('afterend',pill)}pill.textContent=count;pill.title=`${count} total colors`}
function render(){const query=$('colorSearch').value.toLowerCase(),list=rows.filter(row=>`${row.brand||''} ${row.type||''} ${row.color||''} ${row.label||''}`.toLowerCase().includes(query));updateTotalCount(list.length);$('paletteList').innerHTML=grouped(list).map(([brand,items])=>`<section class="color-brand-section"><div class="brand-group-head"><b>${esc(brand)}</b><span class="color-count-pill" title="${items.length} colors in ${esc(brand)}">${items.length}</span></div><div class="brand-color-grid">${items.map(row=>`<article class="color-card" data-edit="${esc(row.id)}"><i class="color-swatch" style="background:${esc(row.swatch||fallback(row.color))}"></i><div><h3>${esc(row.color||'Unnamed')}</h3><p>${esc(row.type||'No type')}</p><small>${esc(row.label||'')}</small></div><span class="color-card-status ${row.active!==false?'active':'inactive'}" title="${row.active!==false?'Active':'Inactive'}">${row.active!==false?'✓':'✕'}</span><button type="button" class="small-btn" data-edit-btn="${esc(row.id)}">Edit</button></article>`).join('')}</div></section>`).join('')||'<div class="empty-soft">No colors found.</div>'}
function updateGeneratedLabel(){const value=[$('brand').value,$('type').value,$('color').value].filter(Boolean).join(' - ');$('label').value=value}
function clear(){editing=null;$('colorForm').reset();$('active').checked=true;$('swatchPicker').value='#b8863b';$('swatch').value='';updateGeneratedLabel();$('colorForm').classList.remove('show');$('deleteColor').classList.add('hidden')}
async function load(){rows=await CVDB.select('cv_colors','select=*&order=brand.asc,color.asc');$('brandList').innerHTML=[...new Set(rows.map(row=>row.brand).filter(Boolean))].map(value=>`<option value="${esc(value)}"></option>`).join('');render()}
function openRow(id){const row=rows.find(value=>String(value.id)===String(id));if(!row)return;editing=row;$('colorForm').classList.add('show');['brand','type','color','swatch'].forEach(key=>$(key).value=row[key]||'');$('swatchPicker').value=row.swatch||fallback(row.color);$('active').checked=row.active!==false;updateGeneratedLabel();$('deleteColor').classList.remove('hidden');$('colorForm').scrollIntoView({behavior:'smooth',block:'start'})}
$('newColor').onclick=()=>{clear();$('colorForm').classList.add('show');$('brand').focus()};$('clearColor').onclick=clear;$('colorSearch').oninput=render;$('paletteList').onclick=event=>{const target=event.target.closest('[data-edit-btn],[data-edit]');const id=target?.dataset.editBtn||target?.dataset.edit;if(id)openRow(id)};$('swatchPicker').oninput=event=>$('swatch').value=event.target.value;$('swatch').oninput=event=>{if(/^#[0-9a-f]{6}$/i.test(event.target.value))$('swatchPicker').value=event.target.value};['brand','type','color'].forEach(id=>$(id).addEventListener('input',updateGeneratedLabel));$('useBrand').onclick=()=>$('brand').focus();$('colorForm').onsubmit=async event=>{event.preventDefault();updateGeneratedLabel();const row={brand:$('brand').value.trim(),type:$('type').value.trim(),color:$('color').value.trim(),label:$('label').value,swatch:$('swatch').value||$('swatchPicker').value,active:$('active').checked};editing?await CVDB.patch('cv_colors',`id=eq.${editing.id}`,row):await CVDB.insert('cv_colors',row);toast('Color saved');clear();await load()};$('deleteColor').onclick=async()=>{if(!editing)return;const ok=await confirmAction({title:'Delete Color',message:`Delete ${editing.color||editing.label}?`,details:'This removes the color from the filament palette.',confirmText:'Delete Color'});if(!ok)return;await CVDB.remove('cv_colors',`id=eq.${editing.id}`);toast('Color deleted');clear();await load()};$('label').readOnly=true;load().catch(error=>toast(error.message,'err'));
