initNavigation('print-items.html');

let printRows = [];
let colors = [];
let editingPrintItem = null;
let componentRows = [];
let linkedRows = [];

const $ = id => document.getElementById(id);
const money = value => '$' + Number(value || 0).toFixed(2);
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const STORE = 'cv_print_item_pricing_v2';
const DEFAULTS_STORE = 'cv_print_pricing_defaults_v1';
const SIZE_STORE = 'cv_3d_item_sizes';
const fallbackDefaults = { filamentRate: 0.02, machineRate: 0.75, markupPercent: 100, roundTo: 0.50 };
const fallbackSizes = ['General','Regular','Small','Medium','Large','12oz','8.4oz','Coin Holder','Koozie','Plaque'];

function readJson(key, fallback) { try { return JSON.parse(localStorage.getItem(key) || 'null') || fallback; } catch { return fallback; } }
function writeJson(key, value) { localStorage.setItem(key, JSON.stringify(value)); }
function defaults() { return { ...fallbackDefaults, ...readJson(DEFAULTS_STORE, {}) }; }
function sizes() { return readJson(SIZE_STORE, fallbackSizes); }
function store() { return readJson(STORE, {}); }
function saveStore(sku, data) { const s = store(); s[String(sku)] = data; writeJson(STORE, s); }
function first(item, keys, fallback = '') { for (const k of keys) if (item && item[k] !== undefined && item[k] !== null && String(item[k]).trim() !== '') return item[k]; return fallback; }
function parseArray(value, fallback) { if (Array.isArray(value)) return value; if (!value) return fallback; try { const parsed = JSON.parse(value); return Array.isArray(parsed) ? parsed : fallback; } catch { return fallback; } }
function itemKey(item) { return String(item?.sku ?? item?.item_sku ?? item?.item_id ?? item?.id ?? ''); }
function imageFor(item) { return first(item, ['image_url','image','photo_url','thumbnail_url'], 'images/CajunVeteran 3D Print Logo.png'); }
function visible(item) { const status = String(item.status || '').toLowerCase(); return !(status === 'hidden' || item.hidden === true || item.active === false); }
function stockState(item) { const stock = Number(first(item, ['stock','qty','quantity','on_hand'], 0)); return stock <= 0 ? {key:'out', label:'Out of Stock', value:stock} : {key:'good', label:'In Stock', value:stock}; }
function minutes(h, m) { return Number(h || 0) * 60 + Number(m || 0); }
function formatMinutes(total) { const h = Math.floor(Number(total || 0) / 60); const m = Math.round(Number(total || 0) % 60); return `${h}h ${String(m).padStart(2,'0')}m`; }
function roundTo(value, step) { step = Number(step || 0.5); return step > 0 ? Math.ceil(Number(value || 0) / step) * step : Number(value || 0); }
function calc(components = componentRows) { const d = defaults(); const grams = components.reduce((s,r)=>s+Number(r.grams||0),0); const totalMinutes = components.reduce((s,r)=>s+minutes(r.hours,r.minutes),0); const filamentCost = grams * Number(d.filamentRate); const machineCost = (totalMinutes/60) * Number(d.machineRate); const baseCost = filamentCost + machineCost; const suggested = roundTo(baseCost * (1 + Number(d.markupPercent)/100), Number(d.roundTo)); return { grams, totalMinutes, filamentCost, machineCost, baseCost, suggested, ...d }; }
function pricingFor(item) { const key = itemKey(item); const s = store()[key] || {}; const comps = parseArray(item.price_components, s.components || []); const linked = parseArray(item.linked_items, s.linked || []); const c = comps.length ? calc(comps) : null; return { components: comps, linked, suggested: Number(item.suggested_price || s.suggested || c?.suggested || 0) }; }
function colorValue(color) { return `${color.brand || ''}||${color.type || ''}||${color.color || color.label || ''}`; }
function colorRec(value) { return colors.find(c => colorValue(c) === value); }
function colorName(value) { const rec = colorRec(value); if (rec) return rec.color || rec.label || value; const parts = String(value||'').split('||'); return parts[2] || value || ''; }
function colorHex(value) { const rec = colorRec(value); const raw = String(rec?.color || rec?.label || value || '').toLowerCase(); const map = {black:'#111',white:'#eee',red:'#b71c1c',orange:'#f47b20',yellow:'#f3c316',green:'#159947',blue:'#1464d2',purple:'#6936c9',pink:'#e15aa2',gray:'#888',grey:'#888',brown:'#8b5a2b',gold:'#caa45f',silver:'#c0c0c0',teal:'#17a2a6'}; const key = Object.keys(map).find(k => raw.includes(k)); return rec?.swatch || map[key] || '#d8d8d8'; }
function colorOptions(selected='') { return '<option value="">Select filament...</option>' + colors.map(c => { const v = colorValue(c); const label = `${c.brand || 'No Brand'} - ${c.color || c.label || 'Unnamed'}${c.type ? ' / ' + c.type : ''}`; return `<option value="${esc(v)}" ${v === selected ? 'selected' : ''}>${esc(label)}</option>`; }).join(''); }
function colorChips(components) { const vals = []; components.forEach(c => { if (c.color && !vals.includes(c.color)) vals.push(c.color); }); if (!vals.length) return '<div class="print-color-chips empty">No colors assigned</div>'; return `<div class="print-color-chips">${vals.map(v => `<span class="print-color-chip"><i style="background:${esc(colorHex(v))}"></i>${esc(colorName(v))}</span>`).join('')}</div>`; }
function populateSizes(selected='General') { $('category').innerHTML = sizes().map(size => `<option value="${esc(size)}" ${String(size)===String(selected)?'selected':''}>${esc(size)}</option>`).join(''); }
function setPreview(value) { const wrap=$('printImagePreviewWrap'), img=$('printImagePreview'); if (!wrap || !img) return; if (value) { img.src=value; wrap.classList.remove('hidden'); } else { img.removeAttribute('src'); wrap.classList.add('hidden'); } }
function fileToDataUrl(file) { return new Promise((resolve,reject)=>{ const r=new FileReader(); r.onload=()=>resolve(r.result); r.onerror=reject; r.readAsDataURL(file); }); }
function linkedOptions(selected='') { return '<option value="">Select linked item...</option>' + printRows.filter(r => !editingPrintItem || itemKey(r) !== itemKey(editingPrintItem)).map(r => `<option value="${esc(itemKey(r))}" ${String(selected)===itemKey(r)?'selected':''}>${esc(r.name || itemKey(r))} (${esc(itemKey(r))})</option>`).join(''); }
function componentRow(row,index) { return `<div class="pi-component-row" data-c-index="${index}"><label>Part / Color<input data-c-field="name" value="${esc(row.name||'')}"></label><label>Filament Color<select data-c-field="color">${colorOptions(row.color||'')}</select></label><label>Grams<input data-c-field="grams" type="number" step="0.1" value="${Number(row.grams||0)}"></label><label>Hours<input data-c-field="hours" type="number" step="1" value="${Number(row.hours||0)}"></label><label>Minutes<input data-c-field="minutes" type="number" step="1" value="${Number(row.minutes||0)}"></label><label class="inline-check component-check">Required <input data-c-field="required" type="checkbox" ${row.required!==false?'checked':''}></label><button class="small-btn red" type="button" data-remove-component="${index}">Remove</button></div>`; }
function linkedRow(row,index) { return `<div class="pi-linked-row" data-l-index="${index}"><label>Linked Item<select data-l-field="sku">${linkedOptions(row.sku)}</select></label><label>Option Label<input data-l-field="label" value="${esc(row.label||'')}"></label><label class="inline-check component-check">Default Selected <input data-l-field="defaultSelected" type="checkbox" ${row.defaultSelected?'checked':''}></label><button class="small-btn red" type="button" data-remove-linked="${index}">Remove</button></div>`; }
function renderComponents() { $('componentRows').innerHTML = componentRows.map(componentRow).join('') || '<div class="pi-empty-soft">No components added yet.</div>'; $('linkedRows').innerHTML = linkedRows.map(linkedRow).join('') || '<div class="pi-empty-soft">No linked item options added yet.</div>'; renderSummary(); }
function renderSummary() { const c=calc(); const d=defaults(); $('print_time').value = formatMinutes(c.totalMinutes); $('grams').value = `${c.grams.toFixed(1)}g`; $('suggestedPriceBox').textContent = money(c.suggested); $('viewFilamentRate').textContent = d.filamentRate; $('viewMachineRate').textContent = d.machineRate; $('viewMarkupPercent').textContent = d.markupPercent; $('viewRoundTo').textContent = d.roundTo; $('pricingSummary').innerHTML = `<div><span>Total Grams</span><strong>${c.grams.toFixed(1)}g</strong></div><div><span>Total Print Time</span><strong>${formatMinutes(c.totalMinutes)}</strong></div><div><span>Material Cost</span><strong>${money(c.filamentCost)}</strong></div><div><span>Machine Cost</span><strong>${money(c.machineCost)}</strong></div><div><span>Base Cost</span><strong>${money(c.baseCost)}</strong></div><div><span>Suggested</span><strong>${money(c.suggested)}</strong></div>`; }
function stats() { const total = printRows.length; const avg = total ? printRows.reduce((s,r)=>s+Number(r.price||0),0)/total : 0; $('piTotal').textContent=total; $('piAverage').textContent=money(avg); $('piVisible').textContent=printRows.filter(visible).length; $('piOut').textContent=printRows.filter(r=>stockState(r).key==='out').length; }
function render() { const q=($('printItemSearch').value||'').toLowerCase(); const f=$('printItemFilter').value; stats(); const list=printRows.filter(r=>{ const h=`${r.sku||''} ${r.name||''} ${r.category||''}`.toLowerCase(); if(q&&!h.includes(q)) return false; if(f==='visible') return visible(r); if(f==='hidden') return !visible(r); if(f==='out') return stockState(r).key==='out'; return true; }); $('printItemsGrid').innerHTML = list.map(r=>{ const key=itemKey(r); const p=pricingFor(r); const c=p.components.length ? calc(p.components) : null; const stock=stockState(r); const time=c ? formatMinutes(c.totalMinutes) : first(r,['print_time','duration','time'],'-'); return `<article class="print-item-card"><div class="print-item-thumb-wrap"><img class="print-item-thumb" src="${esc(imageFor(r))}" onerror="this.src='images/CajunVeteran 3D Print Logo.png'" alt="${esc(r.name||'Print item')}"></div><div class="print-item-content"><div class="print-item-head"><div class="print-title-block"><h3>${esc(r.name||'Unnamed Item')}</h3><small>SKU: ${esc(key)}</small></div><span class="print-stock-pill ${stock.key}">${stock.label}</span></div><div class="print-price">${money(r.price)}</div><div class="print-suggested">Suggested: <b>${money(p.suggested)}</b></div>${colorChips(p.components)}<div class="print-kpis"><div><span>Stock</span><strong>${stock.value}</strong></div><div><span>Type</span><strong>${esc(r.category||'Other')}</strong></div><div><span>Time</span><strong>${esc(time)}</strong></div></div><div class="print-actions"><button type="button" class="small-btn print-edit-btn" data-edit="${esc(key)}">Edit</button></div></div></article>`; }).join('') || '<div class="color-empty">No print items found.</div>'; }
function clearForm() { editingPrintItem=null; componentRows=[]; linkedRows=[]; $('printItemForm').reset(); populateSizes('General'); $('printItemForm').classList.remove('show'); $('deletePrintItem').classList.add('hidden'); setPreview(''); renderComponents(); }
function openEditor(item) { editingPrintItem=item; const p=pricingFor(item); componentRows=p.components||[]; linkedRows=p.linked||[]; $('printItemForm').classList.add('show'); $('sku').value=itemKey(item); $('name').value=item.name||''; $('price').value=Number(item.price||0); $('stock').value=Number(first(item,['stock','qty','quantity','on_hand'],0)); populateSizes(item.category||'General'); $('status').value=visible(item)?'visible':'hidden'; $('description').value=item.description||item.notes||''; $('image_url').value=first(item,['image_url','image','photo_url','thumbnail_url'],''); setPreview($('image_url').value); $('deletePrintItem').classList.remove('hidden'); renderComponents(); $('printItemForm').scrollIntoView({behavior:'smooth',block:'start'}); }
async function load() { printRows = await CVDB.select('cv_items','select=*&order=name.asc'); try { const data = await CVDB.loadDashboard(); colors = data.colors || []; } catch { try { colors = await CVDB.select('cv_colors','select=*&order=brand.asc,color.asc'); } catch { colors = []; } } populateSizes('General'); renderComponents(); render(); }
async function patchWithFilters(row, minimal) { const candidates=[]; if (editingPrintItem?.id) candidates.push(`id=eq.${editingPrintItem.id}`); if (itemKey(editingPrintItem)) candidates.push(`sku=eq.${encodeURIComponent(itemKey(editingPrintItem))}`); if (editingPrintItem?.item_id) candidates.push(`item_id=eq.${encodeURIComponent(editingPrintItem.item_id)}`); let last; for (const filter of candidates) { try { await CVDB.patch('cv_items', filter, row); return true; } catch(e) { last=e; } } for (const filter of candidates) { try { await CVDB.patch('cv_items', filter, minimal); return true; } catch(e) { last=e; } } if (last) throw last; return false; }
async function saveItem() { const c=calc(); const sku=$('sku').value.trim(); const base={sku,name:$('name').value.trim(),price:Number($('price').value||0),stock:Number($('stock').value||0),category:$('category').value,status:$('status').value,description:$('description').value,image_url:$('image_url').value||null,updated_at:new Date().toISOString()}; if(!base.sku||!base.name) { toast('SKU and Name are required','err'); return; } const pricing={components:componentRows,linked:linkedRows,suggested:c.suggested,grams:c.grams,totalMinutes:c.totalMinutes}; saveStore(base.sku, pricing); const extended={...base,price_components:componentRows,linked_items:linkedRows,suggested_price:c.suggested,total_grams:c.grams,total_print_minutes:c.totalMinutes,filament_cost:c.filamentCost,machine_cost:c.machineCost,print_time:formatMinutes(c.totalMinutes),weight:`${c.grams.toFixed(1)}g`}; if(editingPrintItem) { await patchWithFilters(extended,{name:base.name,price:base.price,stock:base.stock,category:base.category,status:base.status,updated_at:base.updated_at}); const idx=printRows.findIndex(r=>itemKey(r)===itemKey(editingPrintItem)||String(r.id)===String(editingPrintItem.id)); if(idx>=0) printRows[idx]={...printRows[idx],...extended}; editingPrintItem={...editingPrintItem,...extended}; } else { try { await CVDB.insert('cv_items', extended); } catch { await CVDB.insert('cv_items', base); } printRows.push(extended); } toast('Print item saved'); render(); clearForm(); await load(); }
function wire() { $('printItemSearch').oninput=render; $('printItemFilter').onchange=render; $('newPrintItem').onclick=()=>{ clearForm(); $('printItemForm').classList.add('show'); }; $('clearPrintItem').onclick=clearForm; $('addComponent').onclick=()=>{ componentRows.push({name:'',color:'',grams:0,hours:0,minutes:0,required:true}); renderComponents(); }; $('addLinkedItem').onclick=()=>{ linkedRows.push({sku:'',label:'',defaultSelected:false}); renderComponents(); }; document.addEventListener('input',e=>{ const row=e.target.closest('[data-c-index]'); if(row&&e.target.dataset.cField){ const i=Number(row.dataset.cIndex), f=e.target.dataset.cField; componentRows[i][f]=['grams','hours','minutes'].includes(f)?Number(e.target.value||0):e.target.value; renderSummary(); } const l=e.target.closest('[data-l-index]'); if(l&&e.target.dataset.lField) linkedRows[Number(l.dataset.lIndex)][e.target.dataset.lField]=e.target.value; }); document.addEventListener('change',e=>{ const row=e.target.closest('[data-c-index]'); if(row&&e.target.dataset.cField){ const i=Number(row.dataset.cIndex), f=e.target.dataset.cField; componentRows[i][f]=f==='required'?e.target.checked:e.target.value; renderSummary(); } const l=e.target.closest('[data-l-index]'); if(l&&e.target.dataset.lField){ const i=Number(l.dataset.lIndex), f=e.target.dataset.lField; linkedRows[i][f]=f==='defaultSelected'?e.target.checked:e.target.value; renderComponents(); } }); document.addEventListener('click',e=>{ if(e.target.dataset.removeComponent!==undefined){ componentRows.splice(Number(e.target.dataset.removeComponent),1); renderComponents(); } if(e.target.dataset.removeLinked!==undefined){ linkedRows.splice(Number(e.target.dataset.removeLinked),1); renderComponents(); } }); $('printItemsGrid').onclick=e=>{ const btn=e.target.closest('[data-edit]'); if(!btn) return; const row=printRows.find(r=>itemKey(r)===String(btn.dataset.edit)); if(row) openEditor(row); }; $('image_file').onchange=async e=>{ const file=e.target.files&&e.target.files[0]; if(!file) return; $('image_url').value=await fileToDataUrl(file); setPreview($('image_url').value); }; $('removePrintImage').onclick=()=>{ $('image_url').value=''; $('image_file').value=''; setPreview(''); }; $('printItemForm').onsubmit=async e=>{ e.preventDefault(); try { await saveItem(); } catch(err) { console.error(err); toast(`Item was not saved: ${err.message}`,'err'); } }; $('deletePrintItem').onclick=async()=>{ if(!editingPrintItem) return; const ok=await confirmAction({title:'Delete Print Item',message:`Delete ${editingPrintItem.name}?`,details:'This removes the item from the pick list.',confirmText:'Delete Item'}); if(!ok) return; await CVDB.remove('cv_items',`sku=eq.${encodeURIComponent(itemKey(editingPrintItem))}`); toast('Item deleted'); await load(); clearForm(); }; }
wire();
load().catch(e=>toast(e.message,'err'));
