initNavigation('woodworking-jobs.html');
let state={jobs:[],items:[],materials:[],orders:[],plaques:[],editing:null,statusFilter:'all',groupsOpen:{new:true,in_process:true,completed:false,delivered:false}};
const $=id=>document.getElementById(id), money=n=>'$'+Number(n||0).toFixed(2), norm=s=>String(s||'new').toLowerCase().replace(/\s+/g,'_');
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function isPlaqueItem(i){return /plaque/i.test(i?.name||'')}
function nextJobId(){const n=state.jobs.map(j=>Number(String(j.job_id||'').replace(/\D/g,''))).filter(Boolean);return 'W'+String((n.length?Math.max(...n):1000)+1)}
function renderGroups(){const q=$('jobSearch').value.toLowerCase(),groups=['new','in_process','completed','delivered'];$('jobsGrouped').innerHTML=groups.map(g=>{const rows=state.jobs.filter(j=>(state.statusFilter==='all'||norm(j.status)===state.statusFilter)&&norm(j.status)===g&&`${j.job_id} ${j.customer} ${j.project}`.toLowerCase().includes(q));if(!rows.length&&!q)return'';return `<div class="status-group ${state.groupsOpen[g]?'open':''}" data-group="${g}"><div class="status-head"><span>${g.replace('_',' ')}</span><span class="status-count">${rows.length}</span></div><div class="status-body">${rows.map(j=>`<div class="record ${state.editing===j.job_id?'active':''}" data-job="${j.job_id}"><div class="record-top"><b>${j.job_id}</b><b>${money(j.total)}</b></div><div class="record-sub"><span>${esc(j.customer||'')}</span><span>${j.due_date||''}</span></div><div class="order-color-count">${esc(j.project||'')}</div></div>`).join('')||'<div class="record">None</div>'}</div></div>`}).join('')||'<div class="empty-soft">No matching jobs.</div>';renderSide()}
function renderSelects(){$('woodItem').innerHTML='<option value="">Select item...</option>'+state.items.map(i=>`<option value="${i.item_id}">${esc(i.name)}</option>`).join('');$('material').innerHTML='<option value="">Select material...</option>'+state.materials.map(m=>`<option value="${m.id}">${esc(m.material)} - On Hand: ${m.qty||0}, Yield: ${m.yield_qty||'-'}</option>`).join('')}
function renderPlaques(){const item=state.items.find(i=>String(i.item_id)===String($('woodItem').value));$('plaqueBox').classList.toggle('hidden',!isPlaqueItem(item));$('plaques').innerHTML=state.plaques.map((p,i)=>`<div class="plaque-entry"><strong>#${i+1}</strong><input aria-label="Plaque ${i+1} name" placeholder="Name" value="${esc(p.name||'')}" data-plaque-name="${i}"><select aria-label="Plaque ${i+1} rank" data-plaque-rank="${i}"><option ${p.rank==='NCO'?'selected':''}>NCO</option><option ${p.rank==='SNCO'?'selected':''}>SNCO</option><option ${p.rank==='Chief'?'selected':''}>Chief</option></select><input aria-label="Plaque ${i+1} month" placeholder="Month" value="${esc(p.month_promoted||'')}" data-plaque-month="${i}"><button type="button" class="plaque-remove" title="Remove plaque" data-plaque-remove="${i}">×</button></div>`).join('')||'<div class="empty-soft">No plaques added.</div>'}
function renderPrices(){const item=state.items.find(i=>String(i.item_id)===String($('woodItem').value))||{},qty=Number($('qty').value||1),each=Number(item.sale_cost||0);$('itemPrice').textContent=money(each);$('jobTotal').textContent=money(each*qty);if($('matCost'))$('matCost').textContent=money(0)}
function renderSide(){const m=state.materials.find(x=>String(x.id)===String($('material').value));$('materialInfo').innerHTML=m?`<div class="summary-line"><span>Material</span><strong>${esc(m.material)}</strong></div><div class="summary-line"><span>On Hand</span><strong>${m.qty||0}</strong></div><div class="summary-line"><span>Yield</span><strong>${m.yield_qty||'-'}</strong></div><div class="summary-line"><span>Purchase Cost</span><strong>${money(m.cost)}</strong></div>`:'Select a material.';$('jobSummary').innerHTML=`<span class="v7-status">${state.jobs.filter(j=>['new','in_process'].includes(norm(j.status))).length} Active</span>`}
function suggestedMaterial(item){const n=String(item?.name||'').toLowerCase();if(n.includes('plaque'))return state.materials.find(m=>/plaque|poplar/i.test(m.material||''));if(/flag/i.test(n))return state.materials.find(m=>/pine|basswood|flag/i.test(m.material||''));return null}
function clearForm(){state.editing=null;state.plaques=[];$('jobForm').reset();$('orderDate').value=new Date().toISOString().slice(0,10);$('status').value='new';$('qty').value=1;$('material').value='';$('jobTitle').textContent='New Job';$('deleteJob').classList.add('hidden');renderPlaques();renderPrices();renderSide();renderGroups()}
async function load(){const d=await CVDB.loadDashboard();state.jobs=d.woodJobs||[];state.items=d.woodItems||[];state.materials=d.woodMaterials||[];state.orders=d.orders||[];const names=[...new Set([...state.jobs.map(j=>j.customer),...state.orders.map(o=>o.customer)].filter(Boolean))];$('customerList').innerHTML=names.map(n=>`<option value="${esc(n)}"></option>`).join('');renderSelects();clearForm()}
function openJob(id){const j=state.jobs.find(x=>String(x.job_id)===String(id));if(!j)return;state.editing=j.job_id;$('jobTitle').textContent='Job #'+j.job_id;$('customer').value=j.customer||'';$('woodItem').value=j.source_item_id||'';$('status').value=norm(j.status);$('dueDate').value=j.due_date||'';$('orderDate').value=j.created_at?String(j.created_at).slice(0,10):'';$('notes').value=j.notes||'';$('paid').checked=!!j.paid;const uses=Array.isArray(j.material_uses)?j.material_uses:[];const firstUse=uses[0]||{};$('qty').value=Number(firstUse.qty_used||1);$('material').value=firstUse.material_id!=null?String(firstUse.material_id):'';if(!$('material').value){const suggestion=suggestedMaterial(state.items.find(i=>String(i.item_id)===String(j.source_item_id)));$('material').value=suggestion?String(suggestion.id):''}state.plaques=[];if(j.plaque_name)state.plaques.push({name:j.plaque_name,rank:j.plaque_rank||'NCO',month_promoted:j.plaque_month_promoted||''});$('deleteJob').classList.remove('hidden');renderPlaques();renderPrices();renderSide();renderGroups()}
$('jobsGrouped').onclick=e=>{const h=e.target.closest('.status-head');if(h){const g=h.closest('.status-group').dataset.group;state.groupsOpen[g]=!state.groupsOpen[g];renderGroups();return}const r=e.target.closest('[data-job]');if(r)openJob(r.dataset.job)};$('jobSearch').oninput=renderGroups;$('jobStatusFilter').onchange=e=>{state.statusFilter=e.target.value;if(state.statusFilter!=='all')state.groupsOpen[state.statusFilter]=true;renderGroups()};$('newJobBtn').onclick=clearForm;$('clearJob').onclick=clearForm;
$('woodItem').onchange=()=>{const item=state.items.find(i=>String(i.item_id)===String($('woodItem').value));state.plaques=[];if(isPlaqueItem(item))for(let i=0;i<Number($('qty').value||1);i++)state.plaques.push({rank:'NCO'});const m=suggestedMaterial(item);$('material').value=m?String(m.id):'';renderPlaques();renderPrices();renderSide()};$('qty').oninput=()=>{const item=state.items.find(i=>String(i.item_id)===String($('woodItem').value));if(isPlaqueItem(item)){const target=Number($('qty').value||1);while(state.plaques.length<target)state.plaques.push({rank:'NCO'});while(state.plaques.length>target)state.plaques.pop();renderPlaques()}renderPrices()};$('material').onchange=renderSide;$('addPlaque').onclick=()=>{state.plaques.push({rank:'NCO'});$('qty').value=state.plaques.length;renderPlaques();renderPrices()};
document.addEventListener('input',e=>{if(e.target.dataset.plaqueName!==undefined)state.plaques[+e.target.dataset.plaqueName].name=e.target.value;if(e.target.dataset.plaqueMonth!==undefined)state.plaques[+e.target.dataset.plaqueMonth].month_promoted=e.target.value});document.addEventListener('change',e=>{if(e.target.dataset.plaqueRank!==undefined)state.plaques[+e.target.dataset.plaqueRank].rank=e.target.value});document.addEventListener('click',e=>{if(e.target.dataset.plaqueRemove!==undefined){state.plaques.splice(+e.target.dataset.plaqueRemove,1);$('qty').value=Math.max(1,state.plaques.length);renderPlaques();renderPrices()}});
$('deleteJob').onclick=async()=>{if(!state.editing)return;const ok=await confirmAction({title:'Delete Woodworking Job',message:`Delete job ${state.editing}?`,details:'This cannot be undone.',confirmText:'Delete Job'});if(!ok)return;await CVDB.remove('cv_woodworking_jobs',`job_id=eq.${encodeURIComponent(state.editing)}`);toast('Job deleted');await load()};
$('jobForm').onsubmit=async e=>{e.preventDefault();const item=state.items.find(i=>String(i.item_id)===String($('woodItem').value))||{},job_id=state.editing||nextJobId(),first=state.plaques[0]||{},qty=Number($('qty').value||1);const row={job_id,customer:$('customer').value,source_item_id:$('woodItem').value,project:item.name||'',status:$('status').value,due_date:$('dueDate').value||null,paid:$('paid').checked,notes:$('notes').value,total:Number(item.sale_cost||0)*qty,plaque_name:first.name||'',plaque_rank:first.rank||'',plaque_month_promoted:first.month_promoted||'',material_uses:$('material').value?[{material_id:$('material').value,qty_used:qty}]:[],updated_at:new Date().toISOString()};if(state.editing)await CVDB.patch('cv_woodworking_jobs',`job_id=eq.${encodeURIComponent(job_id)}`,row);else await CVDB.insert('cv_woodworking_jobs',row);toast('Job saved');await load()};load().catch(e=>toast(e.message,'err'));
