
const STORAGE_KEY='inventory_orders_store_v9';
function loadStore(){const r=localStorage.getItem(STORAGE_KEY);if(!r){const init={items:[],orders:[],colors:[]};localStorage.setItem(STORAGE_KEY,JSON.stringify(init));return init;}try{return JSON.parse(r);}catch(e){return {items:[],orders:[],colors:[]}}}
function saveStore(s){localStorage.setItem(STORAGE_KEY,JSON.stringify(s))}
function currency(v){if(v===''||v===null||v===undefined)return'';return `$${Number(v).toFixed(2)}`}
function byPriority(a,b){return Number(a.priority||9)-Number(b.priority||9)}
function fmtDate(s){ if(!s) return ''; if(/^\d{4}-\d{2}-\d{2}$/.test(s)){ const [y,m,d]=s.split('-').map(Number); return new Date(y,m-1,d).toLocaleDateString(); } try{ return new Date(s).toLocaleDateString(); }catch{ return s; } }
function statusLabel(v){if(v==='in_progress')return'In Process';if(v==='completed'||v==='ready')return'Completed';if(v==='shipped')return'Shipped/Delivered';return'New'}
function orderSubtotal(store, order){ try{ const lines=Array.isArray(order.lines)?order.lines:[]; return lines.reduce((sum,l)=>{ const it=(store.items||[]).find(i=>i.sku===l.sku); const price=Number(it?.price||0); const qty=Number(l?.qty||0); return sum + (isNaN(price)||isNaN(qty)?0: price*qty); },0);}catch(e){return 0;} }
function orderAdjustment(order, subtotal){ const t=order?.discountType||'none'; const v=Number(order?.discountValue||0); if(t==='percent') return Math.max(0, subtotal*(isNaN(v)?0:v/100)); if(t==='amount') return Math.max(0, isNaN(v)?0:v); return 0; }
function orderSurcharge(order, subtotal){ const t=order?.surchargeType||'none'; const v=Number(order?.surchargeValue||0); if(t==='percent') return Math.max(0, subtotal*(isNaN(v)?0:v/100)); if(t==='amount') return Math.max(0, isNaN(v)?0:v); return 0; }
function orderFinalTotal(store, order){ const sub=orderSubtotal(store,order); const adj=orderAdjustment(order, sub); const sur=orderSurcharge(order, sub); return Math.max(0, sub - adj + sur); }

// Public Items and Orders (unchanged)
function renderItemsPublic(){const s=loadStore();const q=(document.getElementById('searchItems')?.value||'').toLowerCase();const f=document.getElementById('filterAvailability')?.value||'all';const tbody=document.getElementById('itemsTable');if(!tbody)return;tbody.innerHTML='';s.items.filter(i=>i.visible!==false).filter(i=>{if(f==='in')return Number(i.qty||0)>0;if(f==='out')return Number(i.qty||0)<=0;return true}).filter(i=>`${i.sku} ${i.name} ${i.desc||''}`.toLowerCase().includes(q)).forEach(i=>{const tr=document.createElement('tr');const dims=[i.length,i.width,i.height].filter(v=>v!==''&&v!==undefined&&v!==null).join(' x ');const colors=(i.colors||[]).map(cid=>(s.colors.find(c=>c.id===cid)?.label)||cid).join(', ');tr.innerHTML=`<td class="img-cell">${i.image?`<img class="img-thumb" src="${i.image}" alt="${i.name||'item'}"/>`:``}</td><td>${i.sku||''}</td><td>${i.name||''}</td><td><span class="desc">${i.desc||''}</span></td><td>${i.size||''}</td><td><span class="dim-badge">${dims}</span></td><td class="colors-list">${colors}</td><td>${currency(i.price)}</td><td>${Number(i.qty||0)>0?`<span class="badge ok">In stock (${i.qty})</span>`:`<span class="badge muted">Out of stock</span>`}</td>`;tbody.appendChild(tr)});tbody.querySelectorAll('.img-thumb').forEach(img=>{img.style.cursor='pointer';img.addEventListener('click',()=>openImageModal(img.src,img.alt))})}

function renderOrdersPublic(){const s=loadStore();const filter=document.getElementById('orderStatusFilter')?.value||'all';const tbodyA=document.getElementById('ordersTableActive');const tbodyC=document.getElementById('ordersTableCompleted');if(!tbodyA||!tbodyC)return;tbodyA.innerHTML='';tbodyC.innerHTML='';s.orders.slice().sort(byPriority).forEach(o=>{const lines=Array.isArray(o.lines)?o.lines:[];const items=lines.map(l=>{const it=s.items.find(ii=>ii.sku===l.sku),name=it?it.name:l.sku;return `${name} × ${l.qty}`}).join('<br>');const total=orderFinalTotal(s,o).toFixed(2);const tr=document.createElement('tr');tr.className=`st-${o.status}`;tr.innerHTML=`<td><strong>${o.priority||''}</strong></td><td>${o.orderId||''}</td><td>${o.customer||''}</td><td>
<select data-act="pvStatus" data-id="${o.orderId}" style="background:#0a1827;color:#e9edf2;border:1px solid #28415e;border-radius:4px;padding:3px 6px">
  <option value="new" ${o.status==='new'?'selected':''}>New</option>
  <option value="in_progress" ${o.status==='in_progress'?'selected':''}>In Process</option>
  <option value="completed" ${o.status==='completed'?'selected':''}>Completed</option>
  <option value="shipped" ${o.status==='shipped'?'selected':''}>Shipped/Delivered</option>
</select>
</td><td>${fmtDate(o.orderDate)}</td><td>${fmtDate(o.dueDate)}</td><td>${items}</td><td>${total}</td><td>${o.paid?`<span class="badge ok">Paid</span>`:`<span class="badge muted">Unpaid</span>`} <label class="paid-toggle" style="margin-left:6px;cursor:pointer;"><input type="checkbox" data-act="togglePaid" data-id="${o.orderId}" ${o.paid?'checked':''}/> paid</label></td>`;if(o.status==='shipped')tbodyC.appendChild(tr);else if(filter==='all'||o.status===filter||(filter==='completed'&&(o.status==='completed'||o.status==='ready')))tbodyA.appendChild(tr)})}

if (typeof document !== 'undefined'){
  document.addEventListener('change', function(e){
    var t=e.target; if(!t||!t.getAttribute) return;
    if(t.getAttribute('data-act')==='togglePaid'){
      var id=t.getAttribute('data-id'); var s=loadStore(); var idx=s.orders.findIndex(o=>String(o.orderId)==String(id)); if(idx>=0){ s.orders[idx].paid=!!t.checked; saveStore(s); renderOrdersPublic(); }
    }
    if(t.getAttribute('data-act')==='pvStatus'){
      var id2=t.getAttribute('data-id'); var s2=loadStore(); var j=s2.orders.findIndex(o=>String(o.orderId)==String(id2)); if(j>=0){ s2.orders[j].status=t.value; saveStore(s2); renderOrdersPublic(); }
    }
  });
}

function openImageModal(src,cap){const m=document.getElementById('imgModal'),i=document.getElementById('modalImg'),c=document.getElementById('modalCaption');if(!m)return;i.src=src;c.textContent=cap||'';m.classList.remove('hidden');m.setAttribute('aria-hidden','false')}function closeImageModal(){const m=document.getElementById('imgModal');if(!m)return;m.classList.add('hidden');m.setAttribute('aria-hidden','true');const i=document.getElementById('modalImg');if(i)i.src=''}

function setupAdmin(){renderAdminTables();setupForms();setupBackup();refreshColorSelects();refreshOrderItemSelects();suggestNextOrderId();suggestNextSku()}

function renderAdminTables(){const s=loadStore();
  const tc=document.getElementById('colorsTable'); if(tc){ tc.innerHTML=''; s.colors.forEach((c,idx)=>{ const tr=document.createElement('tr'); tr.innerHTML=`<td>${c.brand}</td><td>${c.type}</td><td>${c.color}</td><td><button data-act="editColor" data-idx="${idx}">Edit</button> <button data-act="delColor" data-idx="${idx}" class="danger">Delete</button></td>`; tc.appendChild(tr); }); document.querySelectorAll('[data-act="editColor"]').forEach(b=>b.addEventListener('click',onEditColor)); document.querySelectorAll('[data-act="delColor"]').forEach(b=>b.addEventListener('click',onDelColor)); }
  const ti=document.getElementById('adminItemsTable'); if(ti){ ti.innerHTML=''; s.items.forEach((i,idx)=>{ const tr=document.createElement('tr'); const dims=[i.length,i.width,i.height].filter(v=>v!==''&&v!==undefined&&v!==null).join(' x '); const colors=(i.colors||[]).map(cid=>(s.colors.find(c=>c.id===cid)?.label)||cid).join(', '); tr.innerHTML=`<td class="img-cell">${i.image?`<img class="img-thumb" src="${i.image}" alt="${i.name||'item'}"/>`:``}</td><td>${i.sku||''}</td><td>${i.name||''}</td><td>${i.size||''}</td><td class="colors-list">${colors}</td><td><span class="desc">${i.desc||''}</span></td><td><span class="dim-badge">${dims}</span></td><td>${currency(i.price)}</td><td>${i.qty||0}</td><td>${i.visible===false?'No':'Yes'}</td><td><button data-act="editItem" data-idx="${idx}">Edit</button> <button data-act="delItem" data-idx="${idx}" class="danger">Delete</button></td>`; ti.appendChild(tr); }); document.querySelectorAll('[data-act="editItem"]').forEach(b=>b.addEventListener('click',onEditItem)); document.querySelectorAll('[data-act="delItem"]').forEach(b=>b.addEventListener('click',onDelItem)); }
  const to=document.getElementById('adminOrdersTable'); if(to){ to.innerHTML=''; s.orders.slice().sort(byPriority).forEach((o,idx)=>{ const lines=Array.isArray(o.lines)?o.lines:[]; const text=lines.map(l=>{ const it=s.items.find(x=>x.sku===l.sku); const label=it?it.name:l.sku; return `${label} × ${l.qty}`; }).join(', '); const sub=orderSubtotal(s,o), adj=orderAdjustment(o, sub), sur=orderSurcharge(o, sub), tot=orderFinalTotal(s,o); const tr=document.createElement('tr'); tr.innerHTML=`<td><strong>${o.priority||''}</strong></td><td>${o.orderId||''}</td><td>${o.customer||''}</td><td>${statusLabel(o.status)}</td><td>${fmtDate(o.orderDate)}</td><td>${fmtDate(o.dueDate)}</td><td>${text}</td><td>${sub.toFixed(2)}</td><td>${adj.toFixed(2)}</td><td>${sur.toFixed(2)}</td><td>${tot.toFixed(2)}</td><td>${o.paid?`<span class="badge ok">Paid</span>`:`<span class="badge muted">Unpaid</span>`}</td><td>${o.notes||''}</td><td><button data-act="editOrder" data-idx="${idx}">Edit</button> <button data-act="delOrder" data-idx="${idx}" class="danger">Delete</button></td>`; to.appendChild(tr); }); document.querySelectorAll('[data-act="editOrder"]').forEach(b=>b.addEventListener('click',onEditOrder)); document.querySelectorAll('[data-act="delOrder"]').forEach(b=>b.addEventListener('click',onDelOrder)); }
}

function setupForms(){
  const cf=document.getElementById('colorForm'); if(cf){ cf.addEventListener('submit',e=>{ e.preventDefault(); const fd=new FormData(cf); const brand=fd.get('brand').toString().trim(); const type=fd.get('type').toString().trim(); const color=fd.get('color').toString().trim(); const id=`${brand}||${type}||${color}`.toLowerCase(); const label=`${brand} / ${type} / ${color}`; const s=loadStore(); const idx=s.colors.findIndex(c=>c.id===id); const obj={id,brand,type,color,label}; if(idx>=0) s.colors[idx]=obj; else s.colors.push(obj); saveStore(s); cf.reset(); renderAdminTables(); refreshColorSelects(); }); }
  const f=document.getElementById('itemForm'); const imgIn=document.getElementById('itemImage'); const imgPrev=document.getElementById('imgPreview'); if(imgIn){ imgIn.addEventListener('change', async ()=>{ if(imgIn.files&&imgIn.files[0]){ const data=await fileToDataURL(imgIn.files[0]); imgPrev.src=data; } else imgPrev.src=''; }); }
  const price=document.getElementById('price'); const cost=document.getElementById('costMaterial'); const prof=document.getElementById('profitOut'); function upd(){ const p=parseFloat(price&&price.value||''); const c=parseFloat(cost&&cost.value||''); prof.textContent=(!isNaN(p)&&!isNaN(c))?('$'+(p-c).toFixed(2)):'$0.00'; } if(price) price.addEventListener('input',upd); if(cost) cost.addEventListener('input',upd);
  f.addEventListener('submit', async e=>{ e.preventDefault(); const fd=new FormData(f); const s=loadStore(); const sku=(fd.get('sku')||'').toString().trim()||nextSku(); const idx=s.items.findIndex(i=>i.sku===sku); const file=fd.get('image'); let imageData; if(file&&file.size){ imageData=await fileToDataURL(file); } else if(idx>=0){ imageData=s.items[idx].image; } const colorsSel=document.getElementById('itemColorsSelect'); const colors=colorsSel? Array.from(colorsSel.selectedOptions).map(o=>o.value):[]; const item={ sku, name:fd.get('name').toString().trim(), size:(fd.get('size')||'').toString(), price:fd.get('price')?Number(fd.get('price')):'', costMaterial:fd.get('costMaterial')?Number(fd.get('costMaterial')):'', qty:fd.get('qty')?Number(fd.get('qty')):0, desc:fd.get('desc').toString().trim(), length:fd.get('length')?Number(fd.get('length')):'', width:fd.get('width')?Number(fd.get('width')):'', height:fd.get('height')?Number(fd.get('height')):'', image:imageData, colors, visible:fd.get('visible')==='true' }; if(item.price!=='' && item.costMaterial!=='') item.profit=Number(item.price)-Number(item.costMaterial); if(idx>=0) s.items[idx]=item; else s.items.push(item); saveStore(s); f.reset(); if(imgPrev) imgPrev.src=''; renderAdminTables(); refreshOrderItemSelects(); suggestNextSku(); prof.textContent='$0.00'; });
  const of=document.getElementById('orderForm'); const addBtn=document.getElementById('addLineBtn'); const wrap=of.querySelector('.order-lines');
  function refreshLineColorsSelect(sel,itemSku){ const s=loadStore(); const keep=new Set(Array.from(sel.selectedOptions||[]).map(o=>o.value)); sel.innerHTML=''; s.colors.forEach(c=>{ const o=document.createElement('option'); o.value=c.id; o.textContent=c.label; sel.appendChild(o); }); if(itemSku){ const it=s.items.find(i=>i.sku===itemSku); const defs=it?.colors||[]; defs.forEach(id=>{ const o=[...sel.options].find(x=>x.value===id); if(o) o.selected=true; }); } else { [...sel.options].forEach(o=>{ if(keep.has(o.value)) o.selected=true; }); } }
  function refreshOrderItemSelect(sel){ const s=loadStore(); const cur=sel.value; sel.innerHTML=''; s.items.forEach(i=>{ const o=document.createElement('option'); o.value=i.sku; o.textContent=`${i.name||i.sku} (${i.sku})`; sel.appendChild(o); }); if (cur) sel.value=cur; }

  // NEW: price helper
  function updateLinePrice(lineContainer, sku){
    try { const s=loadStore(); const it=(s.items||[]).find(i=>i.sku===sku); const el=lineContainer.querySelector('.line-price'); if(!el) return; if(it && it.price!=='' && it.price!==undefined && !isNaN(Number(it.price))) el.textContent = `Price: $${Number(it.price).toFixed(2)}`; else el.textContent = 'Price: —'; } catch {}
  }

  function addLine(line){ const d=document.createElement('div'); d.className='order-line'; d.innerHTML=`<label>Item <select class="orderItemSelect"></select><small class="line-price muted"></small></label><label>Qty <input type="number" class="orderQtyInput" min="1" value="${line?.qty||1}" /></label><label>Color(s) <select class="orderLineColorsSelect" multiple size="4"></select></label><button type="button" class="removeLine" title="Remove line">✕</button>`; wrap.appendChild(d); const itemSel=d.querySelector('.orderItemSelect'); const colorSel=d.querySelector('.orderLineColorsSelect'); refreshOrderItemSelect(itemSel); if(line?.sku) itemSel.value=line.sku; refreshLineColorsSelect(colorSel,itemSel.value); if (line?.colors && Array.isArray(line.colors)){ [...colorSel.options].forEach(o=>{ o.selected = line.colors.includes(o.value); }); } updateLinePrice(d, itemSel.value); itemSel.addEventListener('change', ev=>{ refreshLineColorsSelect(colorSel, ev.target.value); updateLinePrice(d, ev.target.value); }); d.querySelector('.removeLine').addEventListener('click', ()=> d.remove()); }

  addBtn.addEventListener('click', ()=> addLine());
  of.addEventListener('submit', (e)=>{ e.preventDefault(); const fd=new FormData(of); const orderId=(fd.get('orderId')||'').toString().trim()||nextOrderId(); const customer=fd.get('customer').toString().trim(); const orderDate=fd.get('orderDate'); const dueDate=fd.get('dueDate'); const status=fd.get('status'); const priority=Number(fd.get('priority')||3); const discountType=(fd.get('discountType')||'none').toString(); const discountValue=Number(fd.get('discountValue')||0); const surchargeType=(fd.get('surchargeType')||'none').toString(); const surchargeValue=Number(fd.get('surchargeValue')||0); const paid=document.getElementById('paidChk')?.checked||false; const notes=fd.get('notes').toString().trim(); const lines=Array.from(wrap.querySelectorAll('.order-line')).map(d=>{ const sku=d.querySelector('.orderItemSelect').value; const qty=Number(d.querySelector('.orderQtyInput').value||1); const colors=Array.from(d.querySelector('.orderLineColorsSelect').selectedOptions).map(o=>o.value); return { sku, qty, colors }; }).filter(l=>l.sku); const s=loadStore(); const idx=s.orders.findIndex(o=>o.orderId===orderId); const o={orderId,customer,lines,orderDate,dueDate,status,priority,discountType,discountValue,surchargeType,surchargeValue,notes,paid}; if (idx>=0) s.orders[idx]=o; else s.orders.push(o); saveStore(s); of.reset(); wrap.innerHTML=''; addLine(); renderAdminTables(); suggestNextOrderId(); });
  wrap.querySelectorAll('.order-line').forEach(d=>{ const rem=d.querySelector('.removeLine'); if(rem) rem.addEventListener('click',()=>d.remove()); const itemSel=d.querySelector('.orderItemSelect'); const colorSel=d.querySelector('.orderLineColorsSelect'); refreshOrderItemSelect(itemSel); refreshLineColorsSelect(colorSel, itemSel.value); updateLinePrice(d, itemSel.value); itemSel.addEventListener('change', ev=>{ refreshLineColorsSelect(colorSel, ev.target.value); updateLinePrice(d, ev.target.value); }); });
}

function onEditColor(e){ const idx=Number(e.target.dataset.idx); const s=loadStore(); const c=s.colors[idx]; const f=document.getElementById('colorForm'); f.brand.value=c.brand; f.type.value=c.type; f.color.value=c.color; f.scrollIntoView({behavior:'smooth'}); }
function onDelColor(e){ const idx=Number(e.target.dataset.idx); const s=loadStore(); if(confirm('Delete this color?')){ const id=s.colors[idx].id; s.colors.splice(idx,1); s.items.forEach(it=>{ if(Array.isArray(it.colors)) it.colors = it.colors.filter(cid=>cid!==id); }); saveStore(s); renderAdminTables(); refreshColorSelects(); } }
function onEditItem(e){ const idx=Number(e.target.dataset.idx); const s=loadStore(); const it=s.items[idx]; const f=document.getElementById('itemForm'); f.sku.value=it.sku||''; f.name.value=it.name||''; document.getElementById('size').value=it.size||'Mini'; f.price.value=it.price||''; const cm=document.getElementById('costMaterial'); if(cm) cm.value=it.costMaterial||''; const pf=document.getElementById('profitOut'); if(pf){ const pN=Number(it.price||0)-Number(it.costMaterial||0); if(!isNaN(pN)) pf.textContent='$'+pN.toFixed(2); } f.qty.value=it.qty||0; f.desc.value=it.desc||''; f.length.value=it.length||''; f.width.value=it.width||''; f.height.value=it.height||''; f.visible.value=(it.visible===false?'false':'true'); const prev=document.getElementById('imgPreview'); if(prev) prev.src=it.image||''; const sel=document.getElementById('itemColorsSelect'); if(sel){ Array.from(sel.options).forEach(o=>{ o.selected=(it.colors||[]).includes(o.value); }); } f.scrollIntoView({behavior:'smooth'}); }
function onDelItem(e){ const idx=Number(e.target.dataset.idx); const s=loadStore(); if(confirm('Delete this item?')){ const sku=s.items[idx].sku; s.items.splice(idx,1); s.orders.forEach(o=>{ if(Array.isArray(o.lines)) o.lines=o.lines.filter(l=>l.sku!==sku); }); saveStore(s); renderAdminTables(); } }
function onEditOrder(e){ const idx=Number(e.target.dataset.idx); const s=loadStore(); const o=s.orders[idx]; const f=document.getElementById('orderForm'); const w=f.querySelector('.order-lines'); f.orderId.value=o.orderId||''; f.customer.value=o.customer||''; f.orderDate.value=o.orderDate||''; f.dueDate.value=o.dueDate||''; f.status.value=o.status||'new'; f.priority.value=o.priority||3; (document.getElementById('discountType')||{}).value=o.discountType||'none'; (document.getElementById('discountValue')||{}).value=(o.discountValue??''); (document.getElementById('surchargeType')||{}).value=o.surchargeType||'none'; (document.getElementById('surchargeValue')||{}).value=(o.surchargeValue??''); const pChk=document.getElementById('paidChk'); if(pChk) pChk.checked=!!o.paid; f.notes.value=o.notes||''; w.innerHTML=''; (o.lines||[]).forEach(line=>{ const d=document.createElement('div'); d.className='order-line'; d.innerHTML=`<label>Item <select class="orderItemSelect"></select><small class="line-price muted"></small></label><label>Qty <input type="number" class="orderQtyInput" min="1" value="${line.qty||1}" /></label><label>Color(s) <select class="orderLineColorsSelect" multiple size="4"></select></label><button type="button" class="removeLine" title="Remove line">✕</button>`; w.appendChild(d); const itemSel=d.querySelector('.orderItemSelect'); const sel=d.querySelector('.orderLineColorsSelect'); const rem=d.querySelector('.removeLine'); if(rem) rem.addEventListener('click',()=>d.remove()); // fill items
 refreshOrderItemSelect(itemSel); itemSel.value=line.sku||''; // fill colors
 sel.innerHTML=''; loadStore().colors.forEach(c=>{ const oOpt=document.createElement('option'); oOpt.value=c.id; oOpt.textContent=c.label; sel.appendChild(oOpt); }); (line.colors||[]).forEach(id=>{ const oElm=[...sel.options].find(x=>x.value===id); if(oElm) oElm.selected=true; }); // default colors on item change
 itemSel.addEventListener('change',ev=>{ const it=loadStore().items.find(i=>i.sku===ev.target.value); const defs=it?.colors||[]; [...sel.options].forEach(o=>o.selected=false); defs.forEach(id=>{ const o2=[...sel.options].find(x=>x.value===id); if(o2) o2.selected=true; }); updateLinePrice(d, ev.target.value); }); // initial price
 updateLinePrice(d, itemSel.value);
 }); f.scrollIntoView({behavior:'smooth'}); }
function onDelOrder(e){ const idx=Number(e.target.dataset.idx); const s=loadStore(); if(confirm('Delete this order?')){ s.orders.splice(idx,1); saveStore(s); renderAdminTables(); suggestNextOrderId(); } }

function setupBackup(){ const dl=document.getElementById('downloadBackup'); if(dl){ dl.addEventListener('click',()=>{ try{ const raw=localStorage.getItem(STORAGE_KEY)||JSON.stringify({items:[],orders:[],colors:[]}); const blob=new Blob([raw],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='inventory_orders_backup.json'; a.click(); }catch(e){ alert('Could not create backup: '+e.message); } }); }
  const restore=document.getElementById('restoreFile'); if(restore){ restore.addEventListener('change',(e)=>{ const file=e.target.files&&e.target.files[0]; if(!file) return; const reader=new FileReader(); reader.onload=()=>{ try{ let data=JSON.parse(reader.result); if(Array.isArray(data)) data={items:[],orders:[],colors:[]}; if(!data||!Array.isArray(data.items)||!Array.isArray(data.orders)){ if(data&&data.store&&Array.isArray(data.store.items)&&Array.isArray(data.store.orders)){ data=data.store; } else { throw new Error('Invalid backup schema. Expected keys: items[], orders[], optional colors[].'); } } if(!Array.isArray(data.colors)) data.colors=[]; data.orders=data.orders.map(o=>({...o, paid:!!o.paid, discountType:o.discountType||'none', discountValue:Number(o.discountValue||0), surchargeType:o.surchargeType||'none', surchargeValue:Number(o.surchargeValue||0)})); data.items=data.items.map(i=>({...i, colors:Array.isArray(i.colors)?i.colors:[]})); saveStore(data); alert('Backup restored successfully.'); renderAdminTables(); refreshColorSelects(); refreshOrderItemSelects(); suggestNextOrderId(); suggestNextSku(); }catch(err){ alert('Restore failed: '+err.message); } finally { restore.value=''; } }; reader.onerror=()=>{ alert('Could not read the selected file.'); restore.value=''; }; reader.readAsText(file); }); }
  const clearBtn=document.getElementById('clearAll'); if(clearBtn){ clearBtn.addEventListener('click',()=>{ if(confirm('This will erase all items, colors, and orders on this device. Continue?')){ saveStore({items:[],orders:[],colors:[]}); renderAdminTables(); refreshColorSelects(); refreshOrderItemSelects(); suggestNextOrderId(); suggestNextSku(); } }); }
}

function refreshColorSelects(){ const s=loadStore(); const sel=document.getElementById('itemColorsSelect'); if(!sel) return; const selected=new Set(Array.from(sel.selectedOptions||[]).map(o=>o.value)); sel.innerHTML=''; s.colors.forEach(c=>{ const o=document.createElement('option'); o.value=c.id; o.textContent=c.label; if(selected.has(o.value)) o.selected=true; sel.appendChild(o); }); }
function refreshOrderItemSelects(){ document.querySelectorAll('.orderItemSelect').forEach(s=> refreshOrderItemSelect(s)); }
function refreshOrderItemSelect(sel){ const s=loadStore(); if(!sel) return; const cur=sel.value; sel.innerHTML=''; s.items.forEach(i=>{ const o=document.createElement('option'); o.value=i.sku; o.textContent=`${i.name||i.sku} (${i.sku})`; sel.appendChild(o); }); if(cur) sel.value=cur; }
function nextOrderId(){ const s=loadStore(); const nums=s.orders.map(o=>Number(o.orderId)).filter(n=>!isNaN(n)); const max=nums.length?Math.max(...nums):100000; return String(max+1); }
function suggestNextOrderId(){ const f=document.getElementById('orderForm'); if(!f) return; if(!f.orderId.value) f.orderId.value=nextOrderId(); }
function nextSku(){ const s=loadStore(); const nums=s.items.map(i=>Number(i.sku)).filter(n=>!isNaN(n)); const max=nums.length?Math.max(...nums):1000000; return String(max+1); }
function suggestNextSku(){ const s=document.getElementById('sku'); if(!s) return; if(!s.value) s.value=nextSku(); }
function fileToDataURL(file){ return new Promise((resolve,reject)=>{ const r=new FileReader(); r.onload=()=>resolve(r.result); r.onerror=reject; r.readAsDataURL(file); }); }
